#!@JBROOT@/bin/sh

@JBROOT@/usr/bin/launchctl unload @ROOTFS@/System/Library/DeveloperModeLaunchDaemons/com.apple.instruments.deviceservice.plist || true

@JBROOT@/usr/bin/launchctl load @JBROOT@/usr/bin/xcodeanydebug/com.apple.instruments.deviceservice.plist
