#!/bin/bash

set -e

if [ -e /usr/bin/xcodeanydebug ]; then
    ldid -M -S/usr/bin/xcodeanydebug/debugserver.entitlements /usr/bin/xcodeanydebug/debugserver
elif [ -e /var/jb/usr/bin/xcodeanydebug ]; then
    ldid -M -S/var/jb/usr/bin/xcodeanydebug/debugserver.entitlements /var/jb/usr/bin/xcodeanydebug/debugserver
fi

killall -9 lockdownd debugserver || true
