#!@JBROOT@/bin/bash

set -e

if [ -f @JBROOT@/usr/bin/xcodeanydebug ]; then
    rm -rf @JBROOT@/usr/bin/xcodeanydebug
fi

mkdir -p @JBROOT@/usr/bin/xcodeanydebug

if [ -f @ROOTFS@/usr/libexec/debugserver ]; then
    # iOS 16+
    cp @ROOTFS@/usr/libexec/debugserver @JBROOT@/usr/bin/xcodeanydebug/debugserver
    
elif [ -d @ROOTFS@/Developer ] && [ "$(ls -A @ROOTFS@/Developer)" ]; then
    if [ -f @ROOTFS@/Developer/usr/bin/debugserver ]; then
        cp @ROOTFS@/Developer/usr/bin/debugserver @JBROOT@/usr/bin/xcodeanydebug/debugserver
    else
        echo -e "\n* debugserver for xcode not found on your device\n\n" >&2
        exit 1
    fi
else
    echo "* Developer Disk Image not mounted, run xcode to connect and pair your device first." >&2
    exit 1
fi
