#!/bin/bash

set -e

if [ -f /usr/bin/xcodeanydebug ]; then
    rm -rf /usr/bin/xcodeanydebug
fi

mkdir -p /usr/bin/xcodeanydebug

if [ -f /rootfs/usr/libexec/debugserver ]; then
    # ios 16.x+
    cp /rootfs/usr/libexec/debugserver /usr/bin/xcodeanydebug/debugserver

elif [ -d /rootfs/Developer ] && [ "$(ls -A /rootfs/Developer)" ]; then
    if [ -f /rootfs/Developer/usr/bin/debugserver ]; then
        cp /rootfs/Developer/usr/bin/debugserver /usr/bin/xcodeanydebug/debugserver
    else
        echo -e "\n* debugserver for xcode not found on your device\n\n" >&2
        exit 1
    fi
else
    echo "* Developer Disk Image not mounted, run xcode to connect and pair your device first." >&2
    exit 1
fi
